const types = {
  SET_EMPLOYMENT_STATUS:'SET_EMPLOYMENT_STATUS',
  SET_PROPRIETORSHIPS_MULTIPLIER: 'SET_PROPRIETORSHIPS_MULTIPLIER',
  SET_FILLING_STATUS: 'SET_FILLING_STATUS',
  DISPLAY_
}

export default types;